services:
  postgres:
    container_name: postgres
    image: postgres:14.5-alpine
    environment:
      POSTGRES_USER: mayur
      POSTGRES_PASSWORD: mayur123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - "9411:9411"
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
  eureka-server:
    image: mayurlomate/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE = docker
    networks:
      - spring
    depends_on:
      - zipkin
  apigw:
    image: mayurlomate/apigw:latest
    container_name: apigw
    ports:
      - "8093:8093"
    environment:
      - SPRING_PROFILES_ACTIVE = docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server
  customer:
    image: mayurlomate/customer:latest
    container_name: customer
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE = docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
      - rabbitmq
  fraud:
    image: mayurlomate/fraud:latest
    container_name: fraud
    ports:
      - "8091:8091"
    environment:
      - SPRING_PROFILES_ACTIVE = docker
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - eureka-server
      - postgres
  notification:
    image: mayurlomate/notification:latest
    container_name: notification
    ports:
      - "8092:8092"
    environment:
      - SPRING_PROFILES_ACTIVE = docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server
      - rabbitmq


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: